# Generated by Django 3.2.9 on 2021-11-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
